### ISSUE TITLE
Office 2016 standard retrieve incomplete

### ISSUE THREAD

**Issue by MaKlgz** [PluginsOCSInventory-NG/officepack#26]
Hello OCSNG team,

I have a problem for retrieving Office 2016 standard key.
![phpmyadmin](https://user-images.githubusercontent.com/8119942/28166728-ab36e89c-680b-11e7-852b-51a070634bd6.PNG)

The bit is 64 but retrieve value is 1.
The key is incomplete, only last five letter be caught.
It is current for retriving Office 2013 key.

Debian 9
php7
OCSNG 2.3.1
officepack 1.1.1
windows agent 2.3.0.0

**Comment by gillesdubois** [comment]
HI,

The bit value is not retrieved for office 2016. 
That why there is a 1 instead of 64 or 32. It's gonna be added to the next plugin version.

Concerning the serial key, that what microsoft let us to inventory.
We can't get the complete serial using a standardized method.

Regards,
Gilles Dubois.

**Comment by MaKlgz** [comment]
Hi gillesdubois,

Thank you for your answer.
Office pack can't get the complete serial key because microsoft do something on it.
Could it issue can be fix?

Thanks.
